### ISSUE TITLE
Error message while implementing

### ISSUE THREAD

**Issue by bartj77** [codyevers/envisionr#1]
Have successfully gotten to the following stage. error messages below. tred again with same result.  This is the error message. complete log of this set of steps copied below.

<html>
<body>

The downloaded binary packages are in 	C:\Users\bartj\AppData\Local\Temp\RtmpWatUZw\downloaded_packages Installing package into ‘C:/Users/bartj/AppData/Local/R/win-library/4.3’ (as ‘lib’ is unspecified) * installing *source* package 'envisionr' ... ** using staged installation ** R ** data ** byte-compile and prepare package for lazy loading Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :    there is no package called 'dtplyr' Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart Execution halted ERROR: lazy loading failed for package 'envisionr' * removing 'C:/Users/bartj/AppData/Local/R/win-library/4.3/envisionr' Warning messages: 1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :   there is no package called ‘envisionr’ 2: In file.copy(savedcopy, lib, recursive = TRUE) :   problem copying C:\Users\bartj\AppData\Local\R\win-library\4.3\00LOCK\fs\libs\x64\fs.dll to C:\Users\bartj\AppData\Local\R\win-library\4.3\fs\libs\x64\fs.dll: Permission denied 3: In i.p(...) :   installation of package ‘C:/Users/bartj/AppData/Local/Temp/RtmpWatUZw/remotes2a93cacd1ab0/codyevers-envisionr-7e0c549’ had non-zero exit status
--
 
> | >
>

</body>
</html>

THIS IS THE COMPLETE SET OF STEPS INVOKED BUT HARD TO READ WHEN CUT AND PASTE. CAN SEND SCREEN SHOT IF USEFUL. 
<html>
<body>

Loading required package: envisionr Downloading GitHub repo codyevers/envisionr@HEAD These packages have more recent versions available. It is recommended to update all of them. Which would you like to update?  1: All                        2: CRAN packages only         3: None                       4: fs (1.6.3 -> 1.6.4) [CRAN]  Enter one or more numbers, or an empty line to skip updates: library(envisionr) Enter one or more numbers, or an empty line to skip updates: 1 fs (1.6.3 -> 1.6.4) [CRAN] Installing 1 packages: fs Installing package into ‘C:/Users/bartj/AppData/Local/R/win-library/4.3’ (as ‘lib’ is unspecified) Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.3:   cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.3/PACKAGES' trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/fs_1.6.4.zip' Content type 'application/zip' length 408899 bytes (399 KB) downloaded 399 KB  package ‘fs’ successfully unpacked and MD5 sums checked Warning: cannot remove prior installation of package ‘fs’ Warning: restored ‘fs’  The downloaded binary packages are in 	C:\Users\bartj\AppData\Local\Temp\RtmpWatUZw\downloaded_packages Installing package into ‘C:/Users/bartj/AppData/Local/R/win-library/4.3’ (as ‘lib’ is unspecified) * installing *source* package 'envisionr' ... ** using staged installation ** R ** data ** byte-compile and prepare package for lazy loading Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :    there is no package called 'dtplyr' Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart Execution halted ERROR: lazy loading failed for package 'envisionr' * removing 'C:/Users/bartj/AppData/Local/R/win-library/4.3/envisionr' Warning messages: 1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :   there is no package called ‘envisionr’ 2: In file.copy(savedcopy, lib, recursive = TRUE) :   problem copying C:\Users\bartj\AppData\Local\R\win-library\4.3\00LOCK\fs\libs\x64\fs.dll to C:\Users\bartj\AppData\Local\R\win-library\4.3\fs\libs\x64\fs.dll: Permission denied 3: In i.p(...) :   installation of package ‘C:/Users/bartj/AppData/Local/Temp/RtmpWatUZw/remotes2a93c36d24bcd/codyevers-envisionr-7e0c549’ had non-zero exit status
--
 
> | >
>

</body>
</html>

**Comment by codyevers** [comment]
dtplyr dependency was missing. this has been addressed. short term fix is to load dtplyr using pacman
`pacman::p_load(dtplyr)`
