### ISSUE TITLE
error in build datacube - IDU reference needed

### ISSUE THREAD

**Issue by bartj77** [codyevers/envisionr#4]
IDU reference appears to be missing in the code:
 
> # build datacube (1 minute) - save as stars object
> dc <- build_datacube(
+   delta_array = da,
+   fields = fields,
+   run_name = 'test_run')
Error in build_datacube(delta_array = da, fields = fields, run_name = "test_run") : 
  IDU reference required

**Comment by codyevers** [comment]
Issue related to missing idu_geom in datacube_func >> build_datacube around L38.

**Comment by codyevers** [comment]
this should be fixed now. Try reinstalling and trying again. Will close for now.
