### ISSUE TITLE
error build datacube 4 year run

### ISSUE THREAD

**Issue by bartj77** [codyevers/envisionr#6]
performed a 4year test run.  csv reads and program works until this step. fishing or ideas but perhaps problem is that its 4 years instead of 40 if that's defined in dimensions somewhare?  or if not, that some of the attributes are never referenced in the 4-year delta?

tested code against the 40 year run again and it works fine to build datacube

> dc4 <- build_datacube(
+   delta_array = da,
+   fields = fields,
+   idu_geom = ref_data$idu_vect,
+   run_name = 'test_run')
Error in st_set_dimensions(st_set_dimensions(stars::st_as_stars(datacube),  : 
  length of values ( 41 ) does not match length of dimension 2 ( 6 )
> View(da)

**Comment by codyevers** [comment]
This has been fixed in the latest commit. Try reinstalling envisionr and seeing if this issue is fixed.

**Comment by bartj77** [comment]
Done and working!
